#!/bin/sh

[ -n "$IPKG_INSTROOT" ] && exit 0
[ "$PKG_UPGRADE" = "1" ] && exit 0

restore="$(uci -q get screenplus.main.restore_official_on_remove)"
[ -n "$restore" ] || restore=1
if [ "$restore" = "1" ] && [ -x /etc/init.d/gl_screen ]; then
	/etc/init.d/gl_screen enable
	/etc/init.d/gl_screen start
fi
exit 0
