#!/bin/sh

[ -n "$IPKG_INSTROOT" ] && exit 0
[ "$PKG_UPGRADE" = "1" ] && exit 0

if [ -x /etc/init.d/gl_screen ]; then
	/etc/init.d/gl_screen enable
	/etc/init.d/gl_screen start
fi
rm -f /tmp/luci-indexcache /tmp/luci-modulecache/* 2>/dev/null
/etc/init.d/rpcd restart 2>/dev/null
exit 0
